---
- copy:
    src: "{{ distribution_id|join('-') }}/"
    dest: /
    mode: preserve

- jm1.pkg.meta_pkg:
    name: "jm1-dev-cpp"
    version: "1"
    depends:
    # shell
    - bash
    - fzf
    # gcc
    - gcc
    - g++
    - gdb
    - gcc-7
    - g++-7
    - gcc-8
    - g++-8
    # clang
    - clang
    - clang-6.0
    - clang-7
    - llvm
    #  - lldb-6.0
    - lldb-7
    - libclang-dev
    - libclang-6.0-dev
    - libclang-7-dev
    - clang-tools-7
    - clang-tidy-7
    # vcs
    - bzr
    - mercurial
    - git
    - subversion
    - myrepos
    # editors
    - vim-nox
    - emacs-nox
    # tools
    - ccache
    - ninja-build
    - cloc
    - cppcheck
    - indent
    - indent-doc
    - doxygen
    - cmake
    - cmake-qt-gui
    - extra-cmake-modules
    - libgoogle-perftools-dev
    - google-perftools
    - nasm
    - valgrind
    - delta
    - c++-annotations-pdf
    - intltool
    - icu-devtools
    - bison
    - flex
    - catch
    - shellcheck
    # packaging
    - quilt
    - packaging-dev
    # core libraries
    - libc++-dev
    - libomp-dev # OpenMP
    - mpi-default-dev
    - libboost-all-dev
    - libboost-doc
    # security libraries
    - libcrypto++-dev
    - libmbedtls-dev
    - libssl-dev
    - libssl-doc
    # computer vision libraries
    - libopencv-highgui-dev
    - libopencv-dev
    # misc libraries
    - freeglut3-dev
    - libusb-1.0-0-dev
    - libusb-1.0-doc
    - libxml2-dev

    # ubuntu-dev-tools requires entries in ppa-ubuntu-toolchain-r.list to be uncommented
    #
    # lldb* packages version-depend on python-lldb-* packages (e.g. lldb-6.0 => python-lldb-6.0),
    #  but python-lldb-* packages conflict with each other (python-lldb-6.0 != python-lldb-4.0).
    #  So only one lldb* package version can be installed at a time. lldb depends e.g. on lldb-4.0 which
    #  because of python-lldb-* conflicts with lldb-6.0, so either install lldb or lldb-6.0.
