---
- set_fact:
    apt_packages: "{{ __apt_packages|list }}"
  when: apt_packages|default(None) == None

- copy:
    src: "{{ ansible_distribution }}-{{ ansible_distribution_version }}/"
    dest: /
    mode: preserve

- include_role:
    name: jm1.virtual_pkg
  vars:
     package_name: "jm1-dev-cpp"
     package_depends: "{{ apt_packages }}"

- set_fact:
    apt_packages: !!null

